"""create_test_session_table_and_realtions

Revision ID: 3d41a53176c9
Revises: e4590df569cc
Create Date: 2025-06-08 22:38:16.615152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d41a53176c9'
down_revision: Union[str, None] = 'e4590df569cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_sessions_name'), 'test_sessions', ['name'], unique=False)
    op.create_index(op.f('ix_test_sessions_owner_id'), 'test_sessions', ['owner_id'], unique=False)
    op.create_table('test_session_questions',
    sa.Column('test_session_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_session_id'], ['test_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('test_session_id', 'question_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_session_questions')
    op.drop_index(op.f('ix_test_sessions_owner_id'), table_name='test_sessions')
    op.drop_index(op.f('ix_test_sessions_name'), table_name='test_sessions')
    op.drop_table('test_sessions')
    # ### end Alembic commands ###
