"""first generate

Revision ID: 4d5024914728
Revises: 
Create Date: 2025-06-06 01:33:57.823365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d5024914728'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=True),
    sa.Column('topic', sa.String(length=100), nullable=True),
    sa.Column('initial_difficulty_estimate', sa.String(length=20), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_created_by_user_id'), 'questions', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_questions_subject'), 'questions', ['subject'], unique=False)
    op.create_index(op.f('ix_questions_topic'), 'questions', ['topic'], unique=False)
    op.create_table('answer_options',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('option_text', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answer_options_question_id'), 'answer_options', ['question_id'], unique=False)
    op.create_table('item_analysis_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('test_session_identifier', sa.String(length=100), nullable=True),
    sa.Column('difficulty_index_p_value', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('discrimination_index', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('responses_analyzed_count', sa.Integer(), nullable=True),
    sa.Column('last_analyzed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'test_session_identifier', name='uq_question_session_analysis')
    )
    op.create_index(op.f('ix_item_analysis_results_question_id'), 'item_analysis_results', ['question_id'], unique=False)
    op.create_index(op.f('ix_item_analysis_results_test_session_identifier'), 'item_analysis_results', ['test_session_identifier'], unique=False)
    op.create_table('student_responses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('student_identifier', sa.String(length=100), nullable=False),
    sa.Column('test_session_identifier', sa.String(length=100), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('selected_option_id', sa.UUID(), nullable=True),
    sa.Column('is_response_correct', sa.Boolean(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['selected_option_id'], ['answer_options.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_responses_question_id'), 'student_responses', ['question_id'], unique=False)
    op.create_index(op.f('ix_student_responses_student_identifier'), 'student_responses', ['student_identifier'], unique=False)
    op.create_index(op.f('ix_student_responses_test_session_identifier'), 'student_responses', ['test_session_identifier'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_responses_test_session_identifier'), table_name='student_responses')
    op.drop_index(op.f('ix_student_responses_student_identifier'), table_name='student_responses')
    op.drop_index(op.f('ix_student_responses_question_id'), table_name='student_responses')
    op.drop_table('student_responses')
    op.drop_index(op.f('ix_item_analysis_results_test_session_identifier'), table_name='item_analysis_results')
    op.drop_index(op.f('ix_item_analysis_results_question_id'), table_name='item_analysis_results')
    op.drop_table('item_analysis_results')
    op.drop_index(op.f('ix_answer_options_question_id'), table_name='answer_options')
    op.drop_table('answer_options')
    op.drop_index(op.f('ix_questions_topic'), table_name='questions')
    op.drop_index(op.f('ix_questions_subject'), table_name='questions')
    op.drop_index(op.f('ix_questions_created_by_user_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
