"""Create roster

Revision ID: bad8f5de1b5d
Revises: 1795ef524f75
Create Date: 2025-06-11 19:12:35.370140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bad8f5de1b5d'
down_revision: Union[str, None] = '1795ef524f75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rosters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rosters_name'), 'rosters', ['name'], unique=False)
    op.create_index(op.f('ix_rosters_owner_id'), 'rosters', ['owner_id'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_identifier', sa.String(length=100), nullable=False),
    sa.Column('roster_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['roster_id'], ['rosters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('roster_id', 'student_identifier', name='_roster_student_uc')
    )
    op.create_index(op.f('ix_students_roster_id'), 'students', ['roster_id'], unique=False)
    op.create_index(op.f('ix_students_student_identifier'), 'students', ['student_identifier'], unique=False)
    op.add_column('questions', sa.Column('correct_answer_text', sa.Text(), nullable=True))
    op.add_column('test_sessions', sa.Column('roster_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'test_sessions', 'rosters', ['roster_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test_sessions', type_='foreignkey')
    op.drop_column('test_sessions', 'roster_id')
    op.drop_column('questions', 'correct_answer_text')
    op.drop_index(op.f('ix_students_student_identifier'), table_name='students')
    op.drop_index(op.f('ix_students_roster_id'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_rosters_owner_id'), table_name='rosters')
    op.drop_index(op.f('ix_rosters_name'), table_name='rosters')
    op.drop_table('rosters')
    # ### end Alembic commands ###
